// ══════════════════════════════════════════
// ASSETS: 21 Ações (7 setores × 3) + 6 FIIs
// ══════════════════════════════════════════
export const assets = [
    // ─── TECNOLOGIA ───
    { ticker: 'TNOV3', name: 'TechNova', type: 'stock', sector: 'Tecnologia', profile: 'Líder consolidada', description: 'Maior corporação de cloud computing do país. Fornece infraestrutura digital para governos e bancos. Pagadora de dividendos estável no setor tech.', initialPrice: 45, volatility: 0.06, momentum: 0.05, dividendYield: 0.03, naturalCauses: JSON.stringify(['Avanço em IA', 'Crise de Semicondutores', 'Falta de devs']), associatedNews: JSON.stringify([]) },
    { ticker: 'BRIS3', name: 'ByteRise', type: 'stock', sector: 'Tecnologia', profile: 'Startup agressiva, volátil', description: 'Startup de cibersegurança e blockchain. Oscila agressivamente, sem lucros estáveis. Aposta pura em hipercrescimento (Growth).', initialPrice: 18, volatility: 0.14, momentum: 0.05, dividendYield: 0.0, naturalCauses: JSON.stringify(['Novo produto revolucionário', 'Mudança na lei de Criptoativos']), associatedNews: JSON.stringify([]) },
    { ticker: 'DGCR3', name: 'DigiCore', type: 'stock', sector: 'Tecnologia', profile: 'Madura, bons dividendos', description: 'Venda de pacotes de dados e softwares corporativos. Uma "vaca leiteira" do setor de software com receita recorrente.', initialPrice: 72, volatility: 0.04, momentum: 0.05, dividendYield: 0.06, naturalCauses: JSON.stringify(['Expansão 5G industrial', 'Tarifação da internet fixa']), associatedNews: JSON.stringify([]) },
    // ─── ENERGIA ───
    { ticker: 'ENVD3', name: 'EnergiaVerde', type: 'stock', sector: 'Energia', profile: 'Renovável, tendência de alta', description: 'Forte presença em fazendas eólicas no Nordeste. Beneficiada por selos ESG. Tendência de longo prazo positiva.', initialPrice: 28, volatility: 0.07, momentum: 0.05, dividendYield: 0.04, naturalCauses: JSON.stringify(['Falta de ventos sazonais', 'Investimentos internacionais em energia limpa']), associatedNews: JSON.stringify([]) },
    { ticker: 'PMAX3', name: 'PetroMax', type: 'stock', sector: 'Energia', profile: 'Petróleo, alta volatilidade', description: 'Exploração e refino de petróleo em águas profundas. Preço atrelado ao barril Brent e políticas de estado. Dividendos enormes.', initialPrice: 55, volatility: 0.12, momentum: 0.05, dividendYield: 0.08, naturalCauses: JSON.stringify(['Redução OPEP+', 'Conflito geopolítico', 'Subsídio aos combustíveis']), associatedNews: JSON.stringify([]) },
    { ticker: 'NUCL3', name: 'NuclearBR', type: 'stock', sector: 'Energia', profile: 'Estável, estatal', description: 'Fornecimento super estável de energia nuclear. Baixíssima volatilidade. Ideal para perfil conservador defensivo.', initialPrice: 90, volatility: 0.03, momentum: 0.05, dividendYield: 0.05, naturalCauses: JSON.stringify(['Desligamento preventivo de turbina', 'Venda da estatal']), associatedNews: JSON.stringify([]) },
    // ─── CONSUMO ───
    { ticker: 'MCFC3', name: 'MercaFácil', type: 'stock', sector: 'Consumo', profile: 'Varejo popular', description: 'Atacadão e supermercados de margem estreita. Sofre muito com inflação e juros altos que corroem a renda das famílias.', initialPrice: 22, volatility: 0.08, momentum: 0.05, dividendYield: 0.02, naturalCauses: JSON.stringify(['Selic alta', 'Inflação de alimentos', 'Liberação de benefícios']), associatedNews: JSON.stringify([]) },
    { ticker: 'LUXM3', name: 'LuxMart', type: 'stock', sector: 'Consumo', profile: 'Varejo premium', description: 'Foco exclusivo classe A: shoppings caros, importados e luxo. Pouco sensível à inflação local. Margens altíssimas.', initialPrice: 110, volatility: 0.05, momentum: 0.05, dividendYield: 0.03, naturalCauses: JSON.stringify(['Variação do Dólar', 'Excesso de milionários']), associatedNews: JSON.stringify([]) },
    { ticker: 'ONLS3', name: 'OnlineShop', type: 'stock', sector: 'Consumo', profile: 'E-commerce agressivo', description: 'Plataforma de e-commerce que briga por preço com o varejo físico. Alta volatilidade, margem sub-zero para ganhar market share.', initialPrice: 12, volatility: 0.13, momentum: 0.05, dividendYield: 0.0, naturalCauses: JSON.stringify(['Isenção de importados', 'Guerra de preços com China']), associatedNews: JSON.stringify([]) },
    // ─── FINANCEIRO ───
    { ticker: 'BSOL3', name: 'BancoSólido', type: 'stock', sector: 'Financeiro', profile: 'Conservador, bons dividendos', description: 'Banco centenário e tradicional. Margens se beneficiam com Selic alta, mas sofrem com caloteiros. Dividendos consistentes.', initialPrice: 85, volatility: 0.04, momentum: 0.05, dividendYield: 0.07, naturalCauses: JSON.stringify(['Inadimplência recorde', 'Nova regulamentação de crédito', 'Selic a 14%']), associatedNews: JSON.stringify([]) },
    { ticker: 'FTPY3', name: 'FinTechPay', type: 'stock', sector: 'Financeiro', profile: 'Disruptivo, volátil', description: 'Banco 100% digital com grande base jovem. Otimizado para o longo prazo (Growth). Sem lucro ainda, apostando em escala.', initialPrice: 15, volatility: 0.15, momentum: 0.05, dividendYield: 0.0, naturalCauses: JSON.stringify(['Regulação de bancos de pagamento', '50 milhões de clientes ativos']), associatedNews: JSON.stringify([]) },
    { ticker: 'INVS3', name: 'InvestCorp', type: 'stock', sector: 'Financeiro', profile: 'Corretora, ganha no volume', description: 'Corretora de valores que lucra com o giro do mercado. Quanto mais trades na bolsa (bull ou bear), mais ela fatura em corretagem.', initialPrice: 35, volatility: 0.09, momentum: 0.05, dividendYield: 0.04, naturalCauses: JSON.stringify(['Volume recorde na B3', 'Nova plataforma de trading']), associatedNews: JSON.stringify([]) },
    // ─── SAÚDE ───
    { ticker: 'VSAU3', name: 'VidaSaúde', type: 'stock', sector: 'Saúde', profile: 'Defensiva, estável', description: 'Operadora de planos de saúde para todo o Brasil. Ativo de defesa: em crises, as pessoas cortam tudo menos saúde.', initialPrice: 48, volatility: 0.05, momentum: 0.05, dividendYield: 0.04, naturalCauses: JSON.stringify(['Mudanças do rol da ANS', 'Desemprego afeta contratos corporativos']), associatedNews: JSON.stringify([]) },
    { ticker: 'BLAB3', name: 'BioLab', type: 'stock', sector: 'Saúde', profile: 'R&D farmacêutica, binária', description: 'Farmacêutica de pesquisa pura. Ou a patente é aprovada e sobe 100%, ou perde tudo. Evento binário clássico.', initialPrice: 20, volatility: 0.16, momentum: 0.05, dividendYield: 0.0, naturalCauses: JSON.stringify(['Fase 3 FDA aprovada', 'Teste clínico falhou']), associatedNews: JSON.stringify([]) },
    { ticker: 'HOSP3', name: 'RedeHosp', type: 'stock', sector: 'Saúde', profile: 'Hospitais, margem apertada', description: 'Rede de hospitais privados. Fatura alto em cirurgias eletivas mas margem é apertada. Pandemias cancelam cirurgias caras.', initialPrice: 38, volatility: 0.07, momentum: 0.05, dividendYield: 0.03, naturalCauses: JSON.stringify(['Pandemia cancela eletivas', 'Novo convênio corporativo']), associatedNews: JSON.stringify([]) },
    // ─── AGRO ───
    { ticker: 'AGFT3', name: 'AgroForte', type: 'stock', sector: 'Agro', profile: 'Exportadora de grãos', description: 'Monstro do agronegócio exportador de soja e milho. Fatura em dólares vendendo para a China. Dólar alto = lucro explosivo.', initialPrice: 62, volatility: 0.09, momentum: 0.05, dividendYield: 0.05, naturalCauses: JSON.stringify(['Seca no Sul', 'Dólar a R$6', 'Embargo chinês']), associatedNews: JSON.stringify([]) },
    { ticker: 'FRIG3', name: 'BoiGlobal', type: 'stock', sector: 'Agro', profile: 'Frigorífico exportador', description: 'Frigorífico que exporta carne bovina para o mundo. Sensível a embargos sanitários e custo do boi gordo.', initialPrice: 30, volatility: 0.10, momentum: 0.05, dividendYield: 0.03, naturalCauses: JSON.stringify(['Embargo sanitário', 'Demanda chinesa recorde', 'Custo do boi gordo']), associatedNews: JSON.stringify([]) },
    { ticker: 'TRTR3', name: 'TerraTech', type: 'stock', sector: 'Agro', profile: 'Máquinas agrícolas', description: 'Fabricante de tratores e colheitadeiras autônomas. Demanda é cíclica e atrelada a financiamentos BNDES subsidiados.', initialPrice: 44, volatility: 0.08, momentum: 0.05, dividendYield: 0.02, naturalCauses: JSON.stringify(['Subsídio BNDES para campo', 'Importação de tratores chineses']), associatedNews: JSON.stringify([]) },
    // ─── MOBILIDADE ───
    { ticker: 'AERV3', name: 'AeroViagem', type: 'stock', sector: 'Mobilidade', profile: 'Cíclica, sensível', description: 'Companhia aérea sensível a combustível (dólar) e demanda (turismo). Despesas em dólar, receitas em real. Risco de falência em crises.', initialPrice: 25, volatility: 0.11, momentum: 0.05, dividendYield: 0.0, naturalCauses: JSON.stringify(['Querosene caro', 'Dólar disparando', 'Nova variante viral']), associatedNews: JSON.stringify([]) },
    { ticker: 'MOVB3', name: 'RotaLivre', type: 'stock', sector: 'Mobilidade', profile: 'Locadora de veículos', description: 'Locadora de carros e frotas corporativas. Sensível ao preço dos combustíveis e à taxa de desemprego regional.', initialPrice: 32, volatility: 0.08, momentum: 0.05, dividendYield: 0.02, naturalCauses: JSON.stringify(['Alta do combustível', 'Expansão de apps de mobilidade']), associatedNews: JSON.stringify([]) },
    { ticker: 'HOTE3', name: 'HotelBrasil', type: 'stock', sector: 'Mobilidade', profile: 'Rede de hotéis, sazonal', description: 'Rede hoteleira premium voltada ao turismo corporativo e lazer. Altamente sazonal: high season é explosão, low season é deserto.', initialPrice: 28, volatility: 0.09, momentum: 0.05, dividendYield: 0.01, naturalCauses: JSON.stringify(['Temporada de verão', 'Pandemia fecha hotéis', 'Megaevento esportivo']), associatedNews: JSON.stringify([]) },
    // ═══ FIIs (3 segmentos × 2 concorrentes) ═══
    { ticker: 'LOGI11', name: 'LogisBR', type: 'fii', sector: 'FIIs', segment: 'Logística', profile: 'Galpões logísticos SP, estável', description: 'FII de galpões logísticos às margens de rodovias de SP. Inquilinos triplo AAA (Amazon, Shopee). Vacância quase zero.', initialPrice: 95, volatility: 0.024, momentum: 0.04, dividendYield: 0.096, naturalCauses: JSON.stringify(['E-commerce em boom', 'Varejista grande quebra']), associatedNews: JSON.stringify([]) },
    { ticker: 'GLOG11', name: 'GalpãoMG', type: 'fii', sector: 'FIIs', segment: 'Logística', profile: 'Galpões logísticos MG, crescimento', description: 'FII de galpões logísticos em MG, concorrente direto do LOGI11. Vacância mais alta mas crescimento mais rápido.', initialPrice: 78, volatility: 0.035, momentum: 0.04, dividendYield: 0.088, naturalCauses: JSON.stringify(['Nova fábrica automotiva em MG', 'Recessão industrial']), associatedNews: JSON.stringify([]) },
    { ticker: 'SHOP11', name: 'ShopMax', type: 'fii', sector: 'FIIs', segment: 'Shopping', profile: 'Shopping capitais, sensível ao varejo', description: 'FII de shoppings nas capitais. Se a economia encolhe, lojistas faturam menos e saem, derrubando o dividendo.', initialPrice: 120, volatility: 0.03, momentum: 0.03, dividendYield: 0.084, naturalCauses: JSON.stringify(['Fim de ano recorde', 'Lockdown severo']), associatedNews: JSON.stringify([]) },
    { ticker: 'MALL11', name: 'MallInterior', type: 'fii', sector: 'FIIs', segment: 'Shopping', profile: 'Shopping interior, defensivo', description: 'FII de shoppings no interior, concorrente do SHOP11. Menos glamour mas custo operacional menor e público fiel.', initialPrice: 88, volatility: 0.025, momentum: 0.03, dividendYield: 0.078, naturalCauses: JSON.stringify(['Novo shopping inaugurado', 'Varejo fraco no interior']), associatedNews: JSON.stringify([]) },
    { ticker: 'PAPF11', name: 'PapelFix', type: 'fii', sector: 'FIIs', segment: 'Papel / CRIs', profile: 'Fundo de papel IPCA, renda passiva', description: 'Fundo de CRIs atrelados a IPCA. Não tem imóvel físico. Quando a inflação sobe, o dividendo multiplica. Proteção ativa.', initialPrice: 98, volatility: 0.015, momentum: 0.04, dividendYield: 0.132, naturalCauses: JSON.stringify(['Calote de CRI', 'Deflação abrupta']), associatedNews: JSON.stringify([]) },
    { ticker: 'HGLG11', name: 'HighYield', type: 'fii', sector: 'FIIs', segment: 'Papel / CRIs', profile: 'CRI de alto risco, dividend yield altíssimo', description: 'Fundo de CRIs lixo com yields obscenos. Aposta em dívidas de empreendimentos arriscados. DY de 18% mas risco de calote massivo.', initialPrice: 65, volatility: 0.04, momentum: 0.04, dividendYield: 0.18, naturalCauses: JSON.stringify(['Default em CRI hoteleiro', 'Inflação alta garante premium']), associatedNews: JSON.stringify([]) },
]
