// Helper to stringify effect JSON compactly
const fx = (o: object) => JSON.stringify(o)

// ═══════════════════════════════════════════════════════════
// EVENT TEMPLATES: 30+ unified events (Cards + News merged)
// Each has: text (title/body/expertTip) + mechanical effect
// ═══════════════════════════════════════════════════════════

export const eventTemplates = [
    // ────────────────────────────────────────
    // GLOBAIS POSITIVOS (5)
    // ────────────────────────────────────────
    {
        name: 'Euforia Macroeconômica', icon: '🚀',
        headline: '📈 Todas as ações +10% a +25% — Bull Market!',
        title: 'Fluxo Recorde: Capital Estrangeiro Invade a B3',
        body: 'Investidores internacionais despejam bilhões no mercado brasileiro. PIB surpreende, juros caem, e a bolsa inteira sobe com força. É a festa do bull market.',
        expertTip: 'Cuidado: quando todo mundo compra, quem vai vender? Correções bruscas virão em 2-3 rodadas.',
        expertAnalysis: 'Em euforia máxima, ações beta-alto (BRIS3, FTPY3) exageram no movimento. A grande vencedora estrutural é a InvestCorp (INVS3), que lucra com o giro independente de direção.',
        scope: 'global', category: 'opportunity', isPositive: true, probability: 'very_rare', cooldownRounds: 5,
        effectJson: fx({ target: 'all', priceModifier: { min: 0.10, max: 0.25 }, volatilityModifier: -0.02, trendOverride: 'bullish', duration: 3 }),
        linkedSectors: JSON.stringify(['Tecnologia', 'Energia', 'Consumo', 'Financeiro', 'Saúde', 'Agro', 'Mobilidade']),
    },
    {
        name: 'Real se Valoriza Forte', icon: '💵',
        headline: '📈 Consumo e Mobilidade +8% a +18%',
        title: 'Dólar Despenca: Real se Fortalece com Entrada de Capital',
        body: 'Forte entrada de fluxo estrangeiro fez o dólar desabar. Empresas com custos dolarizados comemoram enquanto exportadoras sofrem.',
        expertTip: 'Fuja do Agro exportador e compre varejo interno e aviação.',
        expertAnalysis: 'Dólar fraco é pancada em exportadoras (AGFT3, PMAX3, FRIG3) mas alívio para AeroViagem (AERV3) que economiza em querosene. Efeito dura 2-3 rodadas.',
        scope: 'global', category: 'economy', isPositive: true, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'sector', targetFilter: 'Consumo', priceModifier: { min: 0.08, max: 0.18 }, trendOverride: 'bullish', duration: 2 }),
        linkedSectors: JSON.stringify(['Consumo', 'Mobilidade']),
    },
    {
        name: 'Boom de ESG Global', icon: '🌱',
        headline: '📈 Energia Renovável +10% a +20%',
        title: 'Fundos Globais Despejam Bilhões em Portfólios Sustentáveis',
        body: 'Movimento coordenado da ONU redireciona capital para mercados emergentes que respeitam limites de carbono. Empresas ESG disparam.',
        expertTip: 'EnergiaVerde (ENVD3) está perfeitamente alinhada. Empresas "sujas" sofrerão saída de fundos gringos.',
        expertAnalysis: 'Capital institucional ignora P/L e compra apenas ativos ESG. ENVD3 dispara. PetroMax (PMAX3) sofre saída de capital. Efeito de 3 rodadas.',
        scope: 'sector', category: 'opportunity', isPositive: true, probability: 'rare', cooldownRounds: 4,
        effectJson: fx({ target: 'sector', targetFilter: 'Energia', priceModifier: { min: 0.10, max: 0.20 }, trendOverride: 'bullish', duration: 3 }),
        linkedSectors: JSON.stringify(['Energia']),
    },
    {
        name: 'Super Safra Recorde', icon: '🌾',
        headline: '📈 Setor Agro +12% a +20% por 3 rodadas',
        title: 'Clima Perfeito Garante Safra Histórica no Centro-Oeste',
        body: 'Chuvas no timing certo e sol abundante levam a soja e o milho a recordes de produtividade. O Brasil lidera as exportações globais.',
        expertTip: 'Compre Agro antes que a colheita seja precificada. AgroForte e TerraTech são os maiores beneficiados.',
        expertAnalysis: 'A AgroForte (AGFT3) fatura em dólar com a soja mais cara; TerraTech (TRTR3) vende tratores com demanda recorde. BoiGlobal (FRIG3) se beneficia do pasto barato.',
        scope: 'sector', category: 'sector', isPositive: true, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'sector', targetFilter: 'Agro', priceModifier: { min: 0.12, max: 0.20 }, trendOverride: 'bullish', duration: 3 }),
        linkedSectors: JSON.stringify(['Agro']),
    },
    {
        name: 'Open Banking Revoluciona', icon: '📱',
        headline: '📈 FinTechPay +15% a +25%',
        title: 'Open Banking e Drex Quebram Oligopólio dos Bancões',
        body: 'BC impõe portabilidade de crédito em 1 minuto. Clientes migram o salário dos bancões tradicionais para fintechs.',
        expertTip: 'FTPY3 vai engolir a carteira do BancoSólido. Mas a longo prazo, o bancão sempre compra as fintechs menores.',
        expertAnalysis: 'A FinTechPay (FTPY3) explode em adoção. BancoSólido (BSOL3) perde comissões e afunda temporariamente. InvestCorp (INVS3) ganha com o volume.',
        scope: 'company', category: 'opportunity', isPositive: true, probability: 'rare', cooldownRounds: 3,
        effectJson: fx({ target: 'company', targetFilter: 'FTPY3', priceModifier: { min: 0.15, max: 0.25 }, trendOverride: 'bullish', duration: 2 }),
        linkedTickers: JSON.stringify(['FTPY3', 'BSOL3']),
    },

    // ────────────────────────────────────────
    // GLOBAIS NEGATIVOS (5)
    // ────────────────────────────────────────
    {
        name: 'Choque de Juros (Copom)', icon: '🏦',
        headline: '📉 Todas as ações -8% a -18% — Selic dispara!',
        title: 'Copom Surpreende: Selic Sobe 1.5% de Uma Vez',
        body: 'O Banco Central elevou a taxa de juros fora do consenso. A curva de juros reagiu violentamente, ações desabam e dinheiro foge para renda fixa.',
        expertTip: 'Saia de ações Growth (BRIS3, FTPY3) e migre para Tesouro Selic ou CDB. FIIs de papel se beneficiam.',
        expertAnalysis: 'Alta de juros mata ativos de risco. Empresas alavancadas (AERV3) e Growth sem lucro (BRIS3, FTPY3) derretem. Refúgio: NuclearBR (NUCL3), VidaSaúde (VSAU3), PapelFix (PAPF11). Renda fixa sobe de rentabilidade!',
        scope: 'global', category: 'economy', isPositive: false, probability: 'rare', cooldownRounds: 4,
        effectJson: fx({ target: 'all', targetFilter: 'stock', priceModifier: { min: -0.18, max: -0.08 }, volatilityModifier: 0.04, trendOverride: 'bearish', duration: 4, fixedIncomeRateChange: 0.003 }),
        linkedSectors: JSON.stringify(['Financeiro', 'Consumo']),
    },
    {
        name: 'Crise de Crédito', icon: '💳',
        headline: '📉 Consumo e Financeiro -10% a -20%',
        title: 'Inadimplência Generalizada Atinge Pico Histórico',
        body: 'O crédito secou da noite para o dia. Famílias não pagam dívidas, bancos cortam limites, consumo congela. Aversão ao risco extrema.',
        expertTip: 'Saia do consumo agora! Foque em saúde e energia da base. Fintechs sem lucro correm risco de falência.',
        expertAnalysis: 'O "Credit Crunch" mata pela base: BancoSólido (BSOL3) corta crédito → MercaFácil (MCFC3) perde vendas → ByteRise e FinTechPay arriscam falência em 5 rodadas. Refúgio: NuclearBR (NUCL3), VidaSaúde (VSAU3).',
        scope: 'global', category: 'crisis', isPositive: false, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'sector', targetFilter: 'Consumo', priceModifier: { min: -0.20, max: -0.10 }, trendOverride: 'bearish', duration: 3 }),
        linkedSectors: JSON.stringify(['Financeiro', 'Consumo']),
    },
    {
        name: 'Guerra Afeta Produção Mundial', icon: '⚔️',
        headline: '📉 Todas as ações -10% a -20% — Pânico!',
        title: 'Conflito Armado Paralisa Cadeias de Suprimento Globais',
        body: 'Uma ofensiva armada estourou o fornecimento global. Aversão ao risco extrema. A grande maioria das ações sangra no pregão.',
        expertTip: 'Petróleo pode subir isoladamente (PMAX3) enquanto todo o resto cai. Ouro e renda fixa são os refúgios.',
        expertAnalysis: 'Guerras são Bear Market instantâneo. Todas as ações caem exceto petróleo (PMAX3 pode subir com barril caro) e defesas (NUCL3, VSAU3). Duração: 4-5 rodadas até o mercado absorver.',
        scope: 'global', category: 'crisis', isPositive: false, probability: 'very_rare', cooldownRounds: 5,
        effectJson: fx({ target: 'all', priceModifier: { min: -0.20, max: -0.10 }, volatilityModifier: 0.06, trendOverride: 'bearish', duration: 4 }),
    },
    {
        name: 'Dólar Dispara a R$6.50', icon: '💸',
        headline: '📉 Consumo/Mobilidade -8% a -15% | Agro +5% a +10%',
        title: 'Investidores Retiram Capital do Brasil em Massa',
        body: 'Fuga de capitais faz dólar disparar. Importadoras e aéreas sangram enquanto exportadoras comemoram.',
        expertTip: 'Compre AgroForte (exporta em dólar) e venda AeroViagem (paga querosene em dólar).',
        expertAnalysis: 'Dólar forte: AERV3 derrete (custos dolarizados), MCFC3 sofre (importados caros). AGFT3 e FRIG3 sobem (receita dolarizada). Efeito de 2-3 rodadas.',
        scope: 'global', category: 'crisis', isPositive: false, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'sector', targetFilter: 'Mobilidade', priceModifier: { min: -0.15, max: -0.08 }, trendOverride: 'bearish', duration: 2 }),
        linkedSectors: JSON.stringify(['Mobilidade', 'Consumo', 'Agro']),
    },
    {
        name: 'Bear Market Violento', icon: '🐻',
        headline: '📉 Todas as ações -5% a -15%',
        title: 'Pânico Generalizado: Ibovespa Derrete em Sell-off Massivo',
        body: 'O desespero impera. Todas as ações sangram severamente por pura psicologia de massa. Volume de vendas bate recorde histórico.',
        expertTip: 'Não venda no pânico! Quem segura no bear market colhe no bull. InvestCorp lucra com o giro.',
        expertAnalysis: 'Sell-off emocional. Ações beta-alto (BRIS3, FTPY3, ONLS3) caem 2x mais que o mercado. Defensivas (NUCL3, VSAU3) caem menos. Oportunidade de compra para quem tem caixa.',
        scope: 'global', category: 'crisis', isPositive: false, probability: 'uncommon', cooldownRounds: 2,
        effectJson: fx({ target: 'all', targetFilter: 'stock', priceModifier: { min: -0.15, max: -0.05 }, volatilityModifier: 0.08, trendOverride: 'bearish', duration: 2 }),
    },

    // ────────────────────────────────────────
    // SETORIAIS (8)
    // ────────────────────────────────────────
    {
        name: 'Revolução da IA', icon: '🤖',
        headline: '📈 Setor Tecnologia +10% a +20%',
        title: 'Nova Onda de IA Atrai Bilhões do Vale do Silício',
        body: 'Grandes avanços em modelos de linguagem geram furor global. O setor tech nacional ganha momentum com respingos do investimento gringo.',
        expertTip: 'O crescimento futuro é incalculável. Compre no boato, venda no fato.',
        expertAnalysis: 'A ByteRise (BRIS3) sobe pelo sonho (Growth puro). TechNova (TNOV3) vende mais cloud. DigiCore (DGCR3) recebe contratos milionários de cybersecurity. Volatilidade de até 30%.',
        scope: 'sector', category: 'sector', isPositive: true, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'sector', targetFilter: 'Tecnologia', priceModifier: { min: 0.10, max: 0.20 }, trendOverride: 'bullish', duration: 2 }),
        linkedSectors: JSON.stringify(['Tecnologia']),
    },
    {
        name: 'Cerco Regulatório às Big Techs', icon: '⚖️',
        headline: '📉 Setor Tecnologia -5% a -15%',
        title: 'Governo Impõe Taxação e Antitruste ao Setor de Tecnologia',
        body: 'Taxação pesada e regras de antitruste rígidas impostas pelo congresso fazem o setor tech sangrar na bolsa.',
        expertTip: 'TechNova aguenta a regulação por ser grande. ByteRise e DigiCore sofrem mais.',
        expertAnalysis: 'Regulação afeta proporcionalmente mais as menores. BRIS3 e DGCR3 caem mais que TNOV3. Efeito de 3 rodadas.',
        scope: 'sector', category: 'crisis', isPositive: false, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'sector', targetFilter: 'Tecnologia', priceModifier: { min: -0.15, max: -0.05 }, trendOverride: 'bearish', duration: 3 }),
        linkedSectors: JSON.stringify(['Tecnologia']),
    },
    {
        name: 'Pandemia: Estado de Emergência', icon: '🦠',
        headline: '📉 Saúde mista | Mobilidade -15% a -25%',
        title: 'Ministério da Saúde Decreta Emergência para Vírus X',
        body: 'UTIs lotadas, corrida às farmácias. Aviação e turismo colapsam. Saúde privada cancela cirurgias eletivas.',
        expertTip: 'VidaSaúde (VSAU3) fatura enquanto RedeHosp (HOSP3) sofre com eletivas canceladas.',
        expertAnalysis: 'VSAU3 sobe (preventiva), HOSP3 cai (eletivas canceladas), AERV3 derrete (turismo zero), HOTE3 colapsa. Efeito dura 4-5 rodadas.',
        scope: 'sector', category: 'crisis', isPositive: false, probability: 'rare', cooldownRounds: 5,
        effectJson: fx({ target: 'sector', targetFilter: 'Mobilidade', priceModifier: { min: -0.25, max: -0.15 }, trendOverride: 'bearish', duration: 4 }),
        linkedSectors: JSON.stringify(['Mobilidade', 'Saúde']),
    },
    {
        name: 'Combustíveis Disparam', icon: '⛽',
        headline: '📉 Mobilidade -10% a -18%',
        title: 'ICMS e Petrobras Não Chegam em Acordo: Gasolina Dispara',
        body: 'Greve nas refinarias paralisa distribuição. Aviões ficam no chão, locadoras seguram frota. PetroMax se beneficia com o barril caro.',
        expertTip: 'AeroViagem derrete. PetroMax pode subir isoladamente.',
        expertAnalysis: 'AERV3 não fecha a equação de querosene e derrete. RotaLivre (MOVB3) perde locatários de app. PetroMax (PMAX3) sobe com margem maior nos combustíveis.',
        scope: 'sector', category: 'crisis', isPositive: false, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'sector', targetFilter: 'Mobilidade', priceModifier: { min: -0.18, max: -0.10 }, trendOverride: 'bearish', duration: 2 }),
        linkedSectors: JSON.stringify(['Mobilidade', 'Energia']),
    },
    {
        name: 'Vazamento de Dados Massivo', icon: '🔓',
        headline: '📈 DigiCore (DGCR3) +10% a +20%',
        title: 'Vazamento Expõe Dados de 120 Milhões de Brasileiros',
        body: 'A invasão colocou a cibersegurança em xeque. Bancos e varejistas correm para contratar proteção de dados.',
        expertTip: 'DigiCore passará todos os topos anteriores com contratos milionários de urgência.',
        expertAnalysis: 'Pânico institucional: bancos/varejistas assinam contratos milionários com DigiCore (DGCR3). Efeito curto (3 rodadas), depois lateraliza.',
        scope: 'company', category: 'company', isPositive: true, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'company', targetFilter: 'DGCR3', priceModifier: { min: 0.10, max: 0.20 }, trendOverride: 'bullish', duration: 3 }),
        linkedTickers: JSON.stringify(['DGCR3']),
    },
    {
        name: 'Isenção de Importados 50 Dólares', icon: '📦',
        headline: '📉 MercaFácil -10% a -18% | OnlineShop +8% a +15%',
        title: 'Câmara Derruba Veto e Isenta Importados de Impostos',
        body: 'E-commerce chinês volta a operar com preço imbatível. Varejo físico é sentença de morte do margem.',
        expertTip: 'OnlineShop sobe. MercaFácil afunda. Trade perfeito de pares.',
        expertAnalysis: 'ONLS3 sobe com especulação. MCFC3 perde margem contra preço chinês. LuxMart (LUXM3) não é afetada (público diferente). Efeito de 4 rodadas.',
        scope: 'sector', category: 'sector', isPositive: false, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'company', targetFilter: 'MCFC3', priceModifier: { min: -0.18, max: -0.10 }, trendOverride: 'bearish', duration: 4 }),
        linkedTickers: JSON.stringify(['MCFC3', 'ONLS3', 'LUXM3']),
    },
    {
        name: 'BNDES Subsidia Campo', icon: '🚜',
        headline: '📈 TerraTech (TRTR3) +12% a +20%',
        title: 'BNDES Anuncia R$25 Bilhões Subsidiados para Modernização no Campo',
        body: 'Juros abaixo da inflação para trocar frotas antigas por colheitadeiras autônomas. Tratores esgotam nos pátios.',
        expertTip: 'TerraTech (TRTR3) sem estoque. Contratos faturados para 4 rodadas à frente.',
        expertAnalysis: 'Dinheiro subsidiado gera picos de demanda. TRTR3 não tem estoque e os contratos garantem P/L convidativo. Dividendos extraordinários em breve.',
        scope: 'company', category: 'opportunity', isPositive: true, probability: 'rare', cooldownRounds: 4,
        effectJson: fx({ target: 'company', targetFilter: 'TRTR3', priceModifier: { min: 0.12, max: 0.20 }, trendOverride: 'bullish', duration: 3 }),
        linkedTickers: JSON.stringify(['TRTR3']),
    },
    {
        name: 'Ibovespa Renova Máxima', icon: '🏆',
        headline: '📈 InvestCorp (INVS3) +10% a +15% | Volume recorde',
        title: 'Ibovespa Renova Máxima Histórica aos 150.000 Pontos',
        body: 'Euforia contagiante. Investidores pessoa física entram em peso, gerando volume financeiro recorde. Corretoras lucram.',
        expertTip: 'Se todo mundo compra, quem vai vender? Correções virão. Mas a corretora ganha sempre.',
        expertAnalysis: 'InvestCorp (INVS3) lucra independente de direção — ela cobra taxa sobre giro. Bull market longo = corretora nas nuvens.',
        scope: 'company', category: 'opportunity', isPositive: true, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'company', targetFilter: 'INVS3', priceModifier: { min: 0.10, max: 0.15 }, trendOverride: 'bullish', duration: 2 }),
        linkedTickers: JSON.stringify(['INVS3']),
    },

    // ────────────────────────────────────────
    // EMPRESA-ESPECÍFICAS (8)
    // ────────────────────────────────────────
    {
        name: 'Oferta de Compra (M&A)', icon: '💼',
        headline: '📈 Empresa-alvo +15% a +35%',
        title: 'Rumores de Aquisição Bilionária Agitam o Mercado',
        body: 'Vazamento de sala de diretores aponta que um grande conglomerado assinou MOU de confidencialidade para absorver a empresa-alvo.',
        expertTip: 'A comprada sobe (prêmio de aquisição), a compradora sofre diluição.',
        expertAnalysis: 'O alvo da aquisição recebe prêmio gigante (+30%). Compre rápido o alvo! O comprador cai 5% com dívida de aquisição.',
        scope: 'company', category: 'company', isPositive: true, probability: 'rare', cooldownRounds: 4,
        effectJson: fx({ target: 'company', targetFilter: 'TNOV3', priceModifier: { min: 0.15, max: 0.35 }, trendOverride: 'bullish', duration: 2 }),
        linkedTickers: JSON.stringify(['TNOV3', 'BRIS3', 'DGCR3']),
        variablesJson: JSON.stringify({ empresa: ['TechNova', 'ByteRise', 'DigiCore'] }),
    },
    {
        name: 'Fraude Contábil!', icon: '🔥',
        headline: '📉 Empresa-alvo -20% a -40%',
        title: 'CVM Descobre Rombo Bilionário nos Balanços',
        body: 'Whistleblower interno expõe fraudes tributárias em 4 trimestres. Polícia Federal faz operação na sede. Pânico absoluto.',
        expertTip: 'A empresa pode perder 70% de valor e ser banida do IBOV. Não compre achando que é oportunidade!',
        expertAnalysis: 'Evento binário de cauda escura. Fundos são OBRIGADOS a zerar posições. O dinheiro migra para concorrentes do setor (Fly to Quality).',
        scope: 'company', category: 'crisis', isPositive: false, probability: 'rare', cooldownRounds: 5,
        effectJson: fx({ target: 'company', targetFilter: 'MCFC3', priceModifier: { min: -0.40, max: -0.20 }, trendOverride: 'bearish', duration: 3 }),
        linkedTickers: JSON.stringify(['MCFC3', 'LUXM3', 'ONLS3']),
        variablesJson: JSON.stringify({ empresa: ['MercaFácil', 'OnlineShop'] }),
    },
    {
        name: 'BioLab: Tratamento Aprovado!', icon: '💉',
        headline: '📈 BLAB3 +40% a +80% — Patente de bilhões!',
        title: 'ANVISA Aprova Tratamento Revolucionário da BioLab',
        body: 'Três anos de testes e a agência assinou o GO. Farmacêutica explode com patente exclusiva de cura milionária.',
        expertTip: 'Ou sobe 100% ou perde tudo. Este é o evento binário ganhador.',
        expertAnalysis: 'BLAB3 pode entrar em Circuit Breaker para cima. Mas em 2-3 rodadas, o vácuo de repasse gera correção. Seja ágil.',
        scope: 'company', category: 'opportunity', isPositive: true, probability: 'very_rare', cooldownRounds: 6,
        effectJson: fx({ target: 'company', targetFilter: 'BLAB3', priceModifier: { min: 0.40, max: 0.80 }, trendOverride: 'volatile', duration: 2 }),
        linkedTickers: JSON.stringify(['BLAB3']),
    },
    {
        name: 'Calote FinTechPay', icon: '📉',
        headline: '📉 FTPY3 -15% a -25% | Debêntures em risco!',
        title: 'Inadimplência Explode entre Clientes da FinTechPay',
        body: 'O banco digital reporta prejuízo avassalador. Clientes jovens não pagam cartão. Debêntures da empresa tremem.',
        expertTip: 'Se você tem Debênture FinTech, reze. Se tem ação, venda antes do circuit breaker.',
        expertAnalysis: 'O calote afeta não só a ação (FTPY3 -25%) mas também qualquer título de renda fixa atrelado à empresa. Debêntures FinTech podem zerar.',
        scope: 'company', category: 'crisis', isPositive: false, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'company', targetFilter: 'FTPY3', priceModifier: { min: -0.25, max: -0.15 }, trendOverride: 'bearish', duration: 3 }),
        linkedTickers: JSON.stringify(['FTPY3']),
    },
    {
        name: 'PetroMax Descobre Bacia Colossal', icon: '🛢️',
        headline: '📈 PMAX3 +20% a +40% | NuclearBR perde investidores',
        title: 'PetroMax Acha Reserva Superior ao Pré-Sal!',
        body: 'Poço recém-perfurado comprova provisão 5x maior que o pré-sal. Modelo financeiro inteiro da empresa é reescrito para cima.',
        expertTip: 'Quanto mais a PetroMax brilha, mais o governo quer usá-la. Risco político latente!',
        expertAnalysis: 'PMAX3 sobe +40% e puxa o setor de energia. NuclearBR (NUCL3) perde investidores que migram para o petróleo.',
        scope: 'company', category: 'company', isPositive: true, probability: 'rare', cooldownRounds: 5,
        effectJson: fx({ target: 'company', targetFilter: 'PMAX3', priceModifier: { min: 0.20, max: 0.40 }, trendOverride: 'bullish', duration: 3 }),
        linkedTickers: JSON.stringify(['PMAX3', 'NUCL3']),
    },
    {
        name: 'BancoSólido: Lucro Recorde', icon: '🏛️',
        headline: '📈 BSOL3 +8% a +15% — Dividendos explosivos',
        title: 'BancoSólido Reporta Lucro Líquido de R$7 Bilhões',
        body: 'Analistas atônitos com a máquina de spread bancário. JCP será pago na próxima rodada com prêmio de 10%.',
        expertTip: 'Retenha o papel e embolse o dividendo extraordinário.',
        expertAnalysis: 'BSOL3 sobe consistentemente e o maior prêmio é segurar para o JCP/dividendo. Rentista puro.',
        scope: 'company', category: 'company', isPositive: true, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'company', targetFilter: 'BSOL3', priceModifier: { min: 0.08, max: 0.15 }, trendOverride: 'bullish', duration: 2, dividendBonus: 0.50 }),
        linkedTickers: JSON.stringify(['BSOL3']),
    },
    {
        name: 'LuxMart Fecha com LVMH', icon: '💎',
        headline: '📈 LUXM3 +10% a +18% — Exclusividade Dior',
        title: 'Acordo com LVMH Concede Exclusividade de 30 Anos à LuxMart',
        body: 'A marca Dior será repassada com exclusividade para as franqueadas LuxMart na América Latina. Luxo é imune.',
        expertTip: 'Varejo premium opera com margens absurdas e pouca sensibilidade à dor econômica.',
        expertAnalysis: 'Exclusividade + Royalties = valuation sobe por prever recorrência de bilhões. Compre e espere dividendos de marca registrada.',
        scope: 'company', category: 'opportunity', isPositive: true, probability: 'rare', cooldownRounds: 4,
        effectJson: fx({ target: 'company', targetFilter: 'LUXM3', priceModifier: { min: 0.10, max: 0.18 }, trendOverride: 'bullish', duration: 3 }),
        linkedTickers: JSON.stringify(['LUXM3']),
    },
    {
        name: 'Megaevento Esportivo', icon: '⚽',
        headline: '📈 Mobilidade e Hotelaria +10% a +20%',
        title: 'Brasil Sediará Copa do Mundo Sub-20: Turismo em Alta',
        body: 'Milhões de turistas internacionais e domésticos aquecem aviação, hotelaria e locadoras. Demanda explosiva sazonal.',
        expertTip: 'HotelBrasil (HOTE3) e AeroViagem (AERV3) sobem forte mas o efeito é temporário.',
        expertAnalysis: 'HOTE3 sobe com ocupação máxima. AERV3 lucra com malha extra. MOVB3 aluga toda a frota. Efeito de 2-3 rodadas, depois corrige.',
        scope: 'sector', category: 'opportunity', isPositive: true, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'sector', targetFilter: 'Mobilidade', priceModifier: { min: 0.10, max: 0.20 }, trendOverride: 'bullish', duration: 2 }),
        linkedSectors: JSON.stringify(['Mobilidade']),
    },

    // ────────────────────────────────────────
    // FII-ESPECÍFICAS (4)
    // ────────────────────────────────────────
    {
        name: 'Galpões Logísticos: Vacância Zero', icon: '🏭',
        headline: '📈 LOGI11 +8% a +12% — Dividendos +15%',
        title: 'E-commerce Gringa Esgota Galpões Logísticos em SP',
        body: 'Amazon e MercadoLivre ocuparam 100% dos galpões. Reajustes agressivos e vacância zero com inquilino AAA.',
        expertTip: 'Cota sobe e dividendos mensais aumentam 15%. Renda passiva no estado da arte.',
        expertAnalysis: 'LOGI11 reajusta aluguéis com prêmio. Cota testa R$105. Dividendos mensais sobem 15%. GalpãoMG (GLOG11) se beneficia por osmose.',
        scope: 'fii', category: 'fii', isPositive: true, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'fii', targetFilter: 'LOGI11', priceModifier: { min: 0.08, max: 0.12 }, trendOverride: 'bullish', duration: 3 }),
        linkedTickers: JSON.stringify(['LOGI11', 'GLOG11']),
    },
    {
        name: 'Lajes Corporativas Abandonadas', icon: '🏢',
        headline: '📉 SHOP11 -8% a -15% — Home Office vence',
        title: 'Gigante da Faria Lima Devolve 6 Andares de Escritório',
        body: 'Política de home-office esvazia back-offices. Condomínios caríssimos recaem sobre o fundo. Dividendos derretem.',
        expertTip: 'Venda rápido e aloque em PapelFix (PAPF11) ou perca por taxa inerte.',
        expertAnalysis: 'SHOP11 perde receita de 6 lajes mas paga condomínio sozinho. Dividendo mensal é engolido. Migre para PAPF11 (CRIs IPCA).',
        scope: 'fii', category: 'crisis', isPositive: false, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'fii', targetFilter: 'SHOP11', priceModifier: { min: -0.15, max: -0.08 }, trendOverride: 'bearish', duration: 3, vacancyChange: 0.05 }),
        linkedTickers: JSON.stringify(['SHOP11', 'MALL11']),
    },
    {
        name: 'Calote nos CRIs HighYield', icon: '💀',
        headline: '📉 HGLG11 -15% a -25% — Default!',
        title: 'Calote Massivo nos Recebíveis do Fundo HighYield',
        body: 'Dois complexos hoteleiros deram judicial. O fundo perde sua receita principal. DY de 18% era bom demais pra ser verdade.',
        expertTip: 'Dividend Yield de 18% era arriscado demais. A conta chegou.',
        expertAnalysis: 'HGLG11 marca a mercado o papel pro buraco (P/VP e cota derretem 20%). Juros vão a zero. Momento "Risco/Retorno" fatal. PapelFix (PAPF11) é seguro.',
        scope: 'fii', category: 'crisis', isPositive: false, probability: 'rare', cooldownRounds: 5,
        effectJson: fx({ target: 'fii', targetFilter: 'HGLG11', priceModifier: { min: -0.25, max: -0.15 }, trendOverride: 'bearish', duration: 4 }),
        linkedTickers: JSON.stringify(['HGLG11', 'PAPF11']),
    },
    {
        name: 'Inflação Engorda PapelFix', icon: '📊',
        headline: '📈 PAPF11 +5% a +10% — Dividendos multiplicam',
        title: 'Inflação Persistente Engorda Distribuição dos Fundos de Papel',
        body: 'IBGE bate no teto a inflação de combustíveis. O fundo PapelFix atrelado ao IPCA bate metas de receita de um ano sem esforço.',
        expertTip: 'Enquanto a bolsa cai com juros e inflação, PapelFix se empodera. Proteção ativa pura!',
        expertAnalysis: 'CRIs atrelados a IPCA (PAPF11) vivem disso. O aluno que entende hedge comprou PAPF11 e terá IPCA +7%. Fundo sobe, dividendo multiplica.',
        scope: 'fii', category: 'opportunity', isPositive: true, probability: 'uncommon', cooldownRounds: 3,
        effectJson: fx({ target: 'fii', targetFilter: 'PAPF11', priceModifier: { min: 0.05, max: 0.10 }, trendOverride: 'bullish', duration: 3, fixedIncomeRateChange: 0.002 }),
        linkedTickers: JSON.stringify(['PAPF11']),
    },
]
